# Generated by Django 3.2.16 on 2023-02-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_rename_full_name_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='not_approved',
            field=models.BooleanField(default=False),
        ),
    ]
