# Generated by Django 3.2.16 on 2023-02-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20230207_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='approved',
            new_name='not_read',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='not_approved',
            new_name='read',
        ),
    ]
