# Generated by Django 3.2.16 on 2023-03-29 13:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CakeItem',
            fields=[
                ('cake_id', models.AutoField(primary_key=True, serialize=False)),
                ('cake_name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('dietary', models.CharField(max_length=200)),
                ('allergens', models.CharField(max_length=200, null=True)),
                ('cake_selections', models.IntegerField(choices=[(0, 'Chocolate Cakes'), (1, 'Vegan Cakes'), (2, 'New item')], default=3)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('on_menu', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheeseCakes',
            fields=[
                ('cake_id', models.AutoField(primary_key=True, serialize=False)),
                ('cake_name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('dietary', models.CharField(max_length=200)),
                ('allergens', models.CharField(max_length=200, null=True)),
                ('cake_selections', models.IntegerField(choices=[(2, 'New item'), (1, 'Vegan Cakes'), (0, 'Cheese Cakes')], default=3)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('on_menu', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreamCakes',
            fields=[
                ('cake_id', models.AutoField(primary_key=True, serialize=False)),
                ('cake_name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('dietary', models.CharField(max_length=200)),
                ('allergens', models.CharField(max_length=200, null=True)),
                ('cake_selections', models.IntegerField(choices=[(0, 'Cream Cakes'), (1, 'Vegan Cakes'), (2, 'New item')], default=3)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('on_menu', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
