# Generated by Django 3.2.16 on 2023-01-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakeitem',
            name='cake_selections',
            field=models.IntegerField(choices=[(0, 'Chocolate Cakes'), (1, 'Cream cakes'), (2, 'New item')], default=2),
        ),
    ]
