# Generated by Django 3.2.16 on 2023-03-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheesecakes',
            name='cake_selections',
            field=models.IntegerField(choices=[(1, 'Vegan Cakes'), (2, 'New item'), (0, 'Cheese Cakes')], default=3),
        ),
    ]
