# Generated by Django 3.2.16 on 2023-01-28 17:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_cakeitem_cake_selections'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreamCakes',
            fields=[
                ('cake_id', models.AutoField(primary_key=True, serialize=False)),
                ('cake_name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('dietary', models.CharField(max_length=200)),
                ('allergens', models.CharField(max_length=200, null=True)),
                ('cake_selections', models.IntegerField(choices=[(0, 'Chocolate Cakes'), (1, 'Cream cakes'), (2, 'New item')], default=2)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('on_menu', models.BooleanField(default=False)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
