# Generated by Django 3.2.16 on 2023-02-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0005_auto_20230130_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakeitem',
            name='cake_selections',
            field=models.IntegerField(choices=[(0, 'Chocolate Cakes'), (1, 'Vegan Cakes'), (2, 'New item')], default=3),
        ),
        migrations.AlterField(
            model_name='cheesecakes',
            name='cake_selections',
            field=models.IntegerField(choices=[(0, 'Cheese Cakes'), (1, 'Vegan Cakes'), (2, 'New item')], default=3),
        ),
    ]
