# Generated by Django 3.2.16 on 2023-02-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_alter_cheesecakes_cake_selections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheesecakes',
            name='cake_selections',
            field=models.IntegerField(choices=[(1, 'Vegan Cakes'), (0, 'Cheese Cakes'), (2, 'New item')], default=3),
        ),
    ]
